---
# tasks file for correcthorse.mongodb
- assert:
    that:
      - "mongodb_version == 3.0 or mongodb_version == 3.2 or mongodb_version == 3.4"
    msg: "only mongo versions 3.0, 3.2 and 3.4 are supported" 

- name: add mongodb EL repo key
  rpm_key:
    key: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present
  when: ansible_os_family == 'RedHat'

- name: add mongodb EL repo
  template:
    src: mongodb.repo.j2
    dest: "/etc/yum.repos.d/mongodb-org-{{ mongodb_version }}.repo"
  when: ansible_os_family == 'RedHat'

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: configure mongod
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  when: mongodb_install_server
  register: mongodb_configured
  notify: restart mongod

- name: enable mongod
  systemd:
    name: mongod.service
    enabled: yes
    daemon_reload: yes
  when: mongodb_install_server

- name: start mongod
  systemd:
    name: mongod.service
    state: started
  when: mongodb_install_server and not mongodb_configured.changed

